performFeedbackApiMongo:
  image: mongo:3
  restart: always

  ports:
    - 27017:27017

  volumes:
    - ./vol-mongo/:/data/db

# TODO: make node
# node:
#   image: nodejs
#
#   link: performFeedbackApiMongo