performFeedbackApiMongo:
  image: mongo

  ports:
    - 47017:27017

  volumes:
    - ./vol-mongo/:/data/db

mongo-express:
  image: mongo-express

  links:
    - performFeedbackApiMongo

  ports:
   - 8082:8081

  environment:
    - ME_CONFIG_MONGODB_SERVER=performFeedbackApiMongo